#!/bin/bash

# The pre-commit hook does such that all files with icns resource will be in
# the same directory as their temporary resource file
# all we need to do then is iterate over the files with an icns resource
# and Rez file.rsrc -append -o file
# and SetFile -a C file

retrieveIcnsResource () {
    # iterate over all files with find
    for file in $(find .)
    do
        # check if they have a non-empty resource fork and icns resource
        if [[ $(xattr $file) == *"com.apple.ResourceFork"* && $(RezDet -l $file) == *"icns"* ]]
            then
                # compile the icns resource file in the same directory to
                # file
                Rez $file.rsrc -append -o $file
                rm -f $file.rsrc
                SetFile -a C $file
        fi
    done
}
retrieveIcnsResource
git add .
git commit --no-verify -m "Added icons to files; removed resource files."
exit 0
