#!/bin/bash

storeIcnsResource () {
    for file in $(find .)
    do
        if [[ $(xattr $file) == *"com.apple.ResourceFork"* && $(RezDet -l $file) == *"icns"* ]]
            then
                touch $file.rsrc
                DeRez $file -only icns > $file.rsrc
                git add -f $file.rsrc
        fi
    done
}

storeIcnsResource
git commit --no-verify -m "Added icon resource files."
exit 0
